name: Run JAR on Schedule

on:
  schedule:
    # 每天的UTC时间00:00运行
    - cron: '0 0 * * *'

jobs:
  run-jar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Run JAR file
      run: java -jar .github/workflows/weixin-1.0-SNAPSHOT.jar
