name: Run JAR on Schedule

on:
   workflow_dispatch:

jobs:
  run-jar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Run JAR file
      run: java -jar weixin-1.0-SNAPSHOT.jar
