name: Run JAR on Schedule

on:
   workflow_dispatch:

jobs:
  run-jar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8' # 根据项目需要选择JDK版本

    - name: Run JAR file
      run: java -jar path/to/weixin-1.0-SNAPSHOT.jar
